// GENERATED by scripts/embed-migrations.mjs - do not edit.
// Source: drizzle/*.sql, produced by `pnpm db:generate`.

export interface EmbeddedMigration {
  tag: string
  statements: string[]
}

export const MIGRATIONS: readonly EmbeddedMigration[] = [
  {
    "tag": "0000_purple_silver_fox",
    "statements": [
      "CREATE TABLE `app_settings` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL\n);",
      "CREATE TABLE `config_snapshots` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`project_path` text NOT NULL,\n\t`file_path` text NOT NULL,\n\t`content` text NOT NULL,\n\t`content_hash` text NOT NULL,\n\t`reason` text NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL\n);",
      "CREATE INDEX `config_snapshots_file_idx` ON `config_snapshots` (`project_path`,`file_path`,`created_at`);",
      "CREATE TABLE `profiles` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`root` text NOT NULL,\n\t`overlays` text DEFAULT '[]' NOT NULL,\n\t`access` text DEFAULT '[]' NOT NULL,\n\t`model` text,\n\t`effort` text,\n\t`permission_mode` text,\n\t`agent` text,\n\t`mcp` text DEFAULT '[]' NOT NULL,\n\t`opening_prompt` text,\n\t`pinned_order` integer,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL\n);",
      "CREATE UNIQUE INDEX `profiles_name_unique` ON `profiles` (`name`);",
      "CREATE TABLE `projects` (\n\t`path` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`harness_path` text,\n\t`has_claude_dir` integer DEFAULT false NOT NULL,\n\t`inventory` text NOT NULL,\n\t`git` text,\n\t`last_seen_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL\n);",
      "CREATE INDEX `projects_harness_idx` ON `projects` (`harness_path`);"
    ]
  },
  {
    "tag": "0001_calm_cloak",
    "statements": [
      "CREATE TABLE `sessions` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`cwd` text NOT NULL,\n\t`project_path` text,\n\t`argv` text DEFAULT '[]' NOT NULL,\n\t`status` text DEFAULT 'running' NOT NULL,\n\t`started_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,\n\t`ended_at` text,\n\t`duration_ms` integer,\n\t`exit_code` integer\n);",
      "CREATE INDEX `sessions_started_idx` ON `sessions` (`started_at`);",
      "CREATE INDEX `sessions_status_idx` ON `sessions` (`status`);"
    ]
  },
  {
    "tag": "0002_unknown_namorita",
    "statements": [
      "ALTER TABLE `sessions` ADD `profile_id` integer;"
    ]
  },
  {
    "tag": "0003_smart_nightmare",
    "statements": [
      "CREATE TABLE `history_index` (\n\t`file` text PRIMARY KEY NOT NULL,\n\t`bytes` integer NOT NULL,\n\t`indexed_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL\n);",
      "CREATE TABLE `history_prompts` (\n\t`seq` integer PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`project` text NOT NULL,\n\t`at` integer NOT NULL,\n\t`text` text NOT NULL\n);",
      "CREATE INDEX `history_prompts_session_idx` ON `history_prompts` (`session_id`,`seq`);",
      "CREATE TABLE `history_sessions` (\n\t`session_id` text PRIMARY KEY NOT NULL,\n\t`project` text NOT NULL,\n\t`project_key` text NOT NULL,\n\t`prompt_count` integer NOT NULL,\n\t`first_at` integer NOT NULL,\n\t`last_at` integer NOT NULL,\n\t`first_prompt` text NOT NULL,\n\t`transcript_file` text,\n\t`transcript_bytes` integer,\n\t`project_exists` integer DEFAULT false NOT NULL\n);",
      "CREATE INDEX `history_sessions_last_idx` ON `history_sessions` (`last_at`);",
      "CREATE INDEX `history_sessions_project_idx` ON `history_sessions` (`project_key`,`last_at`);"
    ]
  }
]
